name: "🔧 기타"
description: "위의 템플릿에 맞지 않는 다른 유형의 이슈를 작성해 주세요."
body:
  - type: textarea
    attributes:
      label: "📄 이슈 설명"
      description: "이슈의 내용을 설명해 주세요."
      placeholder: "문제 또는 요구 사항을 구체적으로 작성해 주세요."
    validations:
      required: true
